### ISSUE TITLE
Is fgivenx  compatible with emcee?

### ISSUE THREAD

**Issue by yuanzunli** [williamjameshandley/fgivenx#11]
Dear William,

I'm a loyal user of the code fgivenx. I love it very much. Recently I'm using emcee (a very popular MCMC python tool). So I'm wondering whether  fgivenx can be used for the samples generated by emcee? As emcee is now very popular in the astronomy  community. It would be very good if fgivenx can be compatible with emcee. 

emcee: https://emcee.readthedocs.io/en/stable

**Comment by williamjameshandley** [comment]
Hi @yuanzunli. Many thanks for your input. At  the moment there isn't a function to directly import from emcee outputs, although it would be likely relatively straightforward to modify the code in [`fgivenx.samples.samples_from_getdist_chains`](https://github.com/williamjameshandley/fgivenx/blob/e49b03448ad76aa331a3a69fe4d7faf919dcb94e/fgivenx/samples.py#L63) to do the same. I agree that this would be very useful for the community (as I have used emcee in the past), so if you do manage to get this working, I would be very grateful if you submitted it as a pull request so that others can use it too!
